service: dynamic-question-system

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TABLE_NAME: Questions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}/index/*

functions:
  assignQuestionToCycle:
    handler: handler/assignQuestion.handler
    events:
      - schedule:
          rate: cron(0 11 * * MON) # Every Monday 7 PM SGT

  getQuestionForUser:
    handler: handlers/getQuestion.handler
    events:
      - http:
          path: /getQuestion
          method: get
          request:
            parameters:
              querystrings:
                region: true
                userId: true
  addQuestion:
    handler: handlers/addQuestion.handler
    events:
      - http:
          path: /addQuestion
          method: post

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: region
            AttributeType: S
          - AttributeName: cycle
            AttributeType: N
        KeySchema:
          - AttributeName: PK
            KeyType: HASH # Partition key
          - AttributeName: SK
            KeyType: RANGE # Sort key
        GlobalSecondaryIndexes:
          - IndexName: RegionalCycle
            KeySchema:
              - AttributeName: region
                KeyType: HASH
              - AttributeName: cycle
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: RegionalSK
            KeySchema:
              - AttributeName: region
                KeyType: HASH
              - AttributeName: SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  Outputs:
    DynamoDbTableName:
      Description: DynamoDB Table Name
      Value:
        Ref: DynamoDbTable

plugins:
  # - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-offline # used for local execution
